"""
fog/fog_node.py
----------------
Fog Node — subscribes to all sensor topics on AWS IoT Core,
aggregates readings, computes health score, and:
  1. Republishes processed payload to IoT Core (→ SQS → Lambda → DynamoDB)
  2. Sends SNS email DIRECTLY when machine_state == "critical"
     (immediate alert, does not wait for Lambda)
"""
import json, logging, os, sys, threading, time
from datetime import datetime, timezone
sys.path.insert(0, ".")

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from fog.aggregator   import Aggregator
from fog.detection    import AnomalyDetector
from fog.local_state  import state_store
import fog.health_score as hs_module
from iot_client import connect_iot, create_iot_client, get_logger, load_config

logger = get_logger("fog.node")

VALID_SENSORS = {"vibration", "temperature", "current", "acoustic"}

# ── SNS alert (direct from fog node, not via Lambda) ─────────────────────────
_SNS_TOPIC_ARN  = os.environ.get("SNS_TOPIC_ARN", "")
_AWS_REGION     = os.environ.get("AWS_REGION", "us-east-1")
_last_sns_time  = 0          # epoch — throttle to 1 alert per 60 seconds
_SNS_COOLDOWN   = 60         # seconds between consecutive critical alerts

def _send_critical_sns(payload: dict):
    """Send SNS email alert for critical machine state.
    Throttled — will not fire more than once per _SNS_COOLDOWN seconds.
    """
    global _last_sns_time
    if not _SNS_TOPIC_ARN:
        logger.warning("SNS_TOPIC_ARN not set — skipping email alert.")
        return
    now = time.time()
    if now - _last_sns_time < _SNS_COOLDOWN:
        logger.info("SNS cooldown active — skipping duplicate alert.")
        return
    _last_sns_time = now

    try:
        import boto3
        sns = boto3.client("sns", region_name=_AWS_REGION)
        m   = payload.get("metrics", {})
        active = [k for k, v in payload.get("anomalies", {}).items() if v]

        subject = (
            f"🚨 CRITICAL ALERT — Machine {payload['machine_id']} "
            f"Health Score: {payload['health_score']}/100"
        )
        body = f"""
INDUSTRIAL MACHINE CRITICAL HEALTH ALERT
==========================================
Machine ID    : {payload['machine_id']}
Timestamp     : {payload['timestamp']}
Health Score  : {payload['health_score']} / 100
Machine State : {payload['machine_state'].upper()}

--- Aggregated Metrics (last {payload['window_seconds']}s) ---
Vibration RMS   : {m.get('vibration_rms','N/A')} mm/s
Avg Temperature : {m.get('avg_temperature','N/A')} °C
Avg Current     : {m.get('avg_current','N/A')} A
Avg Acoustic    : {m.get('avg_acoustic','N/A')} dB

--- Active Anomalies ---
{chr(10).join('  ⚠ '+a.replace('_',' ').upper() for a in active) or '  None'}

Immediate inspection is recommended.
This alert was generated by the Fog Node (direct SNS publish).
""".strip()

        sns.publish(TopicArn=_SNS_TOPIC_ARN, Subject=subject, Message=body)
        logger.info("SNS critical alert sent to %s", _SNS_TOPIC_ARN)
    except Exception as e:
        logger.error("SNS publish failed: %s", e)


def _build_payload(machine_id, window_seconds, metrics, anomalies, score, state):
    return {
        "machine_id":     machine_id,
        "timestamp":      datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "window_seconds": window_seconds,
        "metrics": {
            "vibration_rms":   metrics.get("vibration_rms"),
            "avg_temperature": metrics.get("avg_temperature"),
            "avg_current":     metrics.get("avg_current"),
            "avg_acoustic":    metrics.get("avg_acoustic"),
        },
        "anomalies": anomalies,
        "health_score":  score,
        "machine_state": state,
    }


def run():
    cfg        = load_config()
    mid        = cfg["machine"]["id"]
    fog_cfg    = cfg["fog"]
    thresholds = fog_cfg["thresholds"]
    window     = int(fog_cfg["aggregation_window_seconds"])
    interval   = int(fog_cfg["dispatch_interval_seconds"])
    sub_topic  = fog_cfg["subscribe_topic"]
    pub_topic  = fog_cfg["processed_topic"]

    aggregator = Aggregator(window_seconds=window)
    detector   = AnomalyDetector(thresholds=thresholds)

    def on_message(client, userdata, msg):
        try:
            data = json.loads(msg.payload.decode())
        except Exception:
            return
        stype = data.get("sensor_type", "").lower()
        if stype not in VALID_SENSORS:
            return
        try:
            value = float(data["value"])
        except (TypeError, ValueError):
            return
        ts = data.get("timestamp", datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
        aggregator.ingest(stype, value, ts)
        state_store.push_waveform(mid, stype, value, ts)
        logger.debug("ingested %s=%.4f", stype, value)

    def on_connect_extra(client, userdata, flags, rc):
        logger.info("Subscribing to '%s'", sub_topic)
        client.subscribe(sub_topic, qos=1)

    client = create_iot_client(
        client_id="imhm-fog-node-01",
        on_message=on_message,
        on_connect_extra=on_connect_extra,
    )
    connect_iot(client)
    logger.info("Fog node active — dispatching every %ds for '%s'", interval, mid)

    try:
        while True:
            time.sleep(interval)
            counts = aggregator.sample_counts()
            if all(v == 0 for v in counts.values()):
                logger.warning("No sensor data yet — skipping dispatch.")
                continue

            metrics        = aggregator.compute_metrics()
            anomalies      = detector.detect(metrics)
            warnings       = detector.detect_warnings(metrics)
            score, mstate  = hs_module.calculate(anomalies, warnings)
            payload        = _build_payload(mid, window, metrics, anomalies, score, mstate)

            # 1) Publish to IoT Core → SQS → Lambda → DynamoDB
            rc = client.publish(pub_topic, json.dumps(payload), qos=1)
            if rc.rc == 0:
                logger.info("[%s] score=%d state=%s samples=%s", mid, score, mstate, counts)
            else:
                logger.warning("IoT Core publish failed rc=%d", rc.rc)

            # 2) Update local in-memory state (for dashboard fallback)
            state_store.update(payload)

            # 3) Send SNS email DIRECTLY if critical (fast alert, no Lambda wait)
            if mstate == "critical":
                threading.Thread(
                    target=_send_critical_sns, args=(payload,), daemon=True
                ).start()

    except KeyboardInterrupt:
        logger.info("Fog node shutting down.")
    finally:
        client.loop_stop()
        client.disconnect()


if __name__ == "__main__":
    run()
